version: "3.8"

services:
  backend:
    ports:
      - "8000:8000"
    build: ./backend/app
    environment:
      - DB_URL=${DB_URL}  # ✅ Use AWS RDS database URL from .env file
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
