version: "3.8"

services:
  backend:
    build: ./backend/app
    depends_on:
      - db
    env_file:
      - ./backend/app/.env
    restart: unless-stopped
    expose:
      - "8000"

  frontend:
    build: ./frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:latest
    env_file:
      - ./backend/app/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

networks:
  default:
    driver: bridge