version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: app/Dockerfile
    depends_on:
      - db
      - chromadb
    env_file:
      - ./backend/app/.env
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - ./backend/alembic/versions:/app/alembic/versions

  frontend:
    build: ./frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:latest
    env_file:
      - ./backend/app/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma_data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8080
      - PERSIST_DIRECTORY=/chroma/chroma_data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
  chroma_data:

networks:
  default:
    driver: bridge
