version: "3.8"

services:
  backend:
    ports:
      - "8000:8000"
    build: ./backend/app
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://user:password@db:5432/pckonfig
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pckonfig
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  pgdata:
