version: "3.8"

services:
  backend:
    ports:
      - "8000:8000"
    build: ./backend/app
    depends_on:
      - db
    env_file:
      - ./backend/app/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount nginx.conf from host
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: