version: "3.8"

services:
  backend:
    build: ./backend/app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://your_user:your_password@your_rds_endpoint/db_name
    depends_on:
      - nginx

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
