"""Add purpose field to SavedBuild

Revision ID: 0cd463f17bf1
Revises: afdcdd264064
Create Date: 2025-03-23 22:44:24.282200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd463f17bf1'
down_revision: Union[str, None] = 'afdcdd264064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_builds', sa.Column('purpose', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_builds', 'purpose')
    # ### end Alembic commands ###
