"""add saved builds and user table to db

Revision ID: afdcdd264064
Revises: 
Create Date: 2025-02-27 18:56:22.226759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdcdd264064'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('saved_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cpu_id', sa.Integer(), nullable=True),
    sa.Column('gpu_id', sa.Integer(), nullable=True),
    sa.Column('motherboard_id', sa.Integer(), nullable=True),
    sa.Column('ram_id', sa.Integer(), nullable=True),
    sa.Column('psu_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('storage_id', sa.Integer(), nullable=True),
    sa.Column('cooler_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['chassis.id'], ),
    sa.ForeignKeyConstraint(['cooler_id'], ['cpu_coolers.id'], ),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpus.id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], ),
    sa.ForeignKeyConstraint(['motherboard_id'], ['motherboards.id'], ),
    sa.ForeignKeyConstraint(['psu_id'], ['psus.id'], ),
    sa.ForeignKeyConstraint(['ram_id'], ['ram.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage_devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_builds_id'), 'saved_builds', ['id'], unique=False)
    op.alter_column('chassis', 'additional_features',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('chassis', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_chassis_id'), 'chassis', ['id'], unique=False)
    op.alter_column('cpu_coolers', 'brand',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('cpu_coolers', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cpu_coolers', 'size',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('cpu_coolers', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.create_index(op.f('ix_cpu_coolers_id'), 'cpu_coolers', ['id'], unique=False)
    op.alter_column('cpus', 'socket',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('cpus', 'threads',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cpus', 'base_clock',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('cpus', 'cache',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('cpus', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_cpus_id'), 'cpus', ['id'], unique=False)
    op.alter_column('gpus', 'brand',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('gpus', 'model',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('gpus', 'memory',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('gpus', 'interface',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('gpus', 'base_clock',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('gpus', 'recommended_wattage',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('gpus', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.create_index(op.f('ix_gpus_id'), 'gpus', ['id'], unique=False)
    op.alter_column('motherboards', 'brand',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('motherboards', 'socket',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('motherboards', 'form_factor',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('motherboards', 'chipset',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('motherboards', 'memory_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('motherboards', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.create_index(op.f('ix_motherboards_id'), 'motherboards', ['id'], unique=False)
    op.alter_column('psus', 'brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('psus', 'wattage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('psus', 'size',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('psus', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.create_index(op.f('ix_psus_id'), 'psus', ['id'], unique=False)
    op.alter_column('ram', 'capacity',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ram', 'speed',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ram', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_ram_id'), 'ram', ['id'], unique=False)
    op.alter_column('storage_devices', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('storage_devices', 'capacity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('storage_devices', 'rpm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('storage_devices', 'read_speed',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('storage_devices', 'write_speed',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('storage_devices', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.create_index(op.f('ix_storage_devices_id'), 'storage_devices', ['id'], unique=False)
    op.drop_column('storage_devices', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_devices', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_storage_devices_id'), table_name='storage_devices')
    op.alter_column('storage_devices', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('storage_devices', 'write_speed',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('storage_devices', 'read_speed',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('storage_devices', 'rpm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('storage_devices', 'capacity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('storage_devices', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index(op.f('ix_ram_id'), table_name='ram')
    op.alter_column('ram', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('ram', 'speed',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('ram', 'capacity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_psus_id'), table_name='psus')
    op.alter_column('psus', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('psus', 'size',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('psus', 'wattage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('psus', 'brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_motherboards_id'), table_name='motherboards')
    op.alter_column('motherboards', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('motherboards', 'memory_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('motherboards', 'chipset',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('motherboards', 'form_factor',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('motherboards', 'socket',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('motherboards', 'brand',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_gpus_id'), table_name='gpus')
    op.alter_column('gpus', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('gpus', 'recommended_wattage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('gpus', 'base_clock',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('gpus', 'interface',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('gpus', 'memory',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('gpus', 'model',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('gpus', 'brand',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_cpus_id'), table_name='cpus')
    op.alter_column('cpus', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('cpus', 'cache',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=1),
               nullable=False)
    op.alter_column('cpus', 'base_clock',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=2),
               nullable=False)
    op.alter_column('cpus', 'threads',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cpus', 'socket',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_cpu_coolers_id'), table_name='cpu_coolers')
    op.alter_column('cpu_coolers', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('cpu_coolers', 'size',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('cpu_coolers', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cpu_coolers', 'brand',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_chassis_id'), table_name='chassis')
    op.alter_column('chassis', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('chassis', 'additional_features',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_saved_builds_id'), table_name='saved_builds')
    op.drop_table('saved_builds')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
